### ISSUE TITLE
Visualizer on dark theme is still white

### ISSUE THREAD

**Issue by Karmalakas** [a85/POSTMan-Chrome-Extension#10145]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

After so called fix on 8.8.0 (which actually is just a workaround) visualizer background is now white. This defeats the purpose of dark theme. A proper default styling should be implemented to support both themes. Also there should be some root CSS classes available for custom styling, eg.:
```css
.PM-theme-light table {
  background-color: light-gray;
}
.PM-theme-dark table {
  background-color: dark-gray;
}
```

### Steps To Reproduce

1. Open _Visualize_ tab in a _Response_ pane

### Environment Information

```markdown
- Operating System: Mac OS
- Platform Type: Native app
- Postman Version: 8.8.0
```
