### ISSUE TITLE
Test fails but exit code is always 0

### ISSUE THREAD

**Issue by danielferromeral** [a85/POSTMan-Chrome-Extension#10183]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

I have a Newman running inside a docker compose with a elasticsearch to query, with a test that always fail, but the container of newman always exit with code 0. That is not the behavior expect, as it should return a code that is not 0 when a test fails. 

### Steps To Reproduce

1. Create the file and folder structure:
Test
| - Postman
| | - Collections
| | | - BasicTestCollection.json
| | - Script
| | | - run-postman-test.sh
| | - Dockerfile
| - docker-compose.yml

2. Fill the BasicTestCollection.json with the next code:
```{
  "info": {
    "_postman_id": "50c29401-0423-40d7-820c-eb7745e33b52",
    "name": "Basic Test Suite:dnsContainer",
    "schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
  },
  "item": [
    {
      "name": "Fail",
      "event": [
        {
          "listen": "test",
          "script": {
            "exec": [
              "pm.test(\"Not failing\", function () {",
              "pm.expect(true).to.eql(false);",
              "});"
            ],
            "type": "text/javascript"
          }
        }
      ],
      "request": {
        "method": "GET",
        "header": [],
        "url": {
          "raw": "http://elasticsearch:9200/_search?pretty=true&q=*:*",
          "host": [
            "http://elasticsearch:9200"
          ],
          "path": [
            "_search?pretty=true&q=*:*"
          ]
        }
      },
      "response": []
    }
  ]
}
```

3. Fill run-postman-test.sh with the next code
```
#!/bin/bash
echo "******************* RUNNING SCRIPT POSTMAN TESTS *******************"
date
sleep 30
echo "******************* RUNNING FUNCTIONAL POSTMAN TESTS *******************"
newman run /etc/newman/BasicTestCollection.json --bail
echo "******************* FUNCTIONAL POSTMAN TESTS DONE *******************"
```

4. Fill Dockerfile with these:
```
FROM postman/newman:5.2

RUN mkdir -p /tmp \
      && install -d -o node /tmp

RUN apk --no-cache add curl jq
RUN npm install -g newman-reporter-htmlextra
RUN npm install -S newman-reporter-htmlextra

USER node

ENTRYPOINT ["/bin/sh", "-c"]
```

5. Fill the docker-compose with these:
```
version: '3'
services:
  elasticsearch:
    networks:
      - conector
    restart: on-failure
    image: elasticsearch:6.6.2
    healthcheck:
      test: curl -s --fail http://localhost:9200/_cluster/health | grep "\"status\":\"green\""
      interval: 10s
      timeout: 5s
      retries: 10
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  postman-newman:
    networks:
      - conector
    restart: on-failure
    build:
      context: ./postman
      dockerfile: Dockerfile
    command: [ "sh /etc/scripts/run-postman-test.sh" ]
    volumes:
      - ./postman/scripts:/etc/scripts
      - ./postman/collections:/etc/newman
    depends_on:
      elasticsearch:
        condition: service_healthy
networks:
  conector:
    driver: bridge
```
6. Run the next command to execute the docker-compose
```
docker-compose up --exit-code-from postman-newman --build --always-recreate-deps --force-recreate
```
7. The output expect from the container of newman should be the next
```
postman-newman_1  | ******************* RUNNING SCRIPT POSTMAN TESTS *******************
postman-newman_1  | Mon Aug  2 11:11:26 UTC 2021
postman-newman_1  | ******************* RUNNING FUNCTIONAL POSTMAN TESTS *******************
postman-newman_1  | newman
postman-newman_1  | 
postman-newman_1  | Basic Test Suite:dnsContainer
postman-newman_1  | 
postman-newman_1  | → Fail
postman-newman_1  |   GET http://elasticsearch:9200/_search?pretty=true&q=*:* [200 OK, 253B, 186ms]
postman-newman_1  |   1. Not failing
postman-newman_1  |   2⠄ AssertionFailure in test-script
postman-newman_1  | 
postman-newman_1  | ┌─────────────────────────┬────────────────────┬───────────────────┐
postman-newman_1  | │                         │           executed │            failed │
postman-newman_1  | ├─────────────────────────┼────────────────────┼───────────────────┤
postman-newman_1  | │              iterations │                  1 │                 0 │
postman-newman_1  | ├─────────────────────────┼────────────────────┼───────────────────┤
postman-newman_1  | │                requests │                  1 │                 0 │
postman-newman_1  | ├─────────────────────────┼────────────────────┼───────────────────┤
postman-newman_1  | │            test-scripts │                  1 │                 1 │
postman-newman_1  | ├─────────────────────────┼────────────────────┼───────────────────┤
postman-newman_1  | │      prerequest-scripts │                  0 │                 0 │
postman-newman_1  | ├─────────────────────────┼────────────────────┼───────────────────┤
postman-newman_1  | │              assertions │                  1 │                 1 │
postman-newman_1  | ├─────────────────────────┴────────────────────┴───────────────────┤
postman-newman_1  | │ total run duration: 250ms                                        │
postman-newman_1  | ├──────────────────────────────────────────────────────────────────┤
postman-newman_1  | │ total data received: 142B (approx)                               │
postman-newman_1  | ├──────────────────────────────────────────────────────────────────┤
postman-newman_1  | │ average response time: 186ms [min: 186ms, max: 186ms, s.d.: 0µs] │
postman-newman_1  | └──────────────────────────────────────────────────────────────────┘
postman-newman_1  | 
postman-newman_1  |   #  failure           detail                              
postman-newman_1  |                                                            
postman-newman_1  |  1.  AssertionError    Not failing                         
postman-newman_1  |                        expected true to deeply equal false 
postman-newman_1  |                        at assertion:0 in test-script       
postman-newman_1  |                        inside "Fail"                       
postman-newman_1  |                                                            
postman-newman_1  |  2.  AssertionFailure                                      
postman-newman_1  |                        Not failing                         
postman-newman_1  |                        at test-script:38:17                
postman-newman_1  |                        inside "Fail"                       
postman-newman_1  | ******************* FUNCTIONAL POSTMAN TESTS DONE *******************
regressiontest_postman-newman_1 exited with code 0
```
Follow with the next
```
Aborting on container exit...
Stopping regressiontest_elasticsearch_1  ... 
Stopping regressiontest_elasticsearch_1  ... done
Process finished with exit code 0
```

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/47207636/127858487-626db90d-5cd6-4067-b9c1-2283454e14f6.png)
![image](https://user-images.githubusercontent.com/47207636/127858552-9256719c-38ce-42aa-8beb-ab756cd6c575.png)
<img width="1375" alt="Captura de pantalla 2021-08-02 a las 14 00 41" src="https://user-images.githubusercontent.com/47207636/127858741-c3ee907b-f30a-4c5a-9484-45c71e42928a.png">

### Environment Information

```markdown
- Operating System: MacOS Big Sur 11.14
- Platform Type: Native App
- Postman/Newman Version: 5.2
```
