### ISSUE TITLE
Documentation Generated from an OpenAPI Specification Fails Validation and Has Incorrect Indentation; Issue Resolution Creates Negative Integer Values

### ISSUE THREAD

**Issue by k98kurz** [a85/POSTMan-Chrome-Extension#10953]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When Documentation is generated from or synchronized to an OenAPI Specification document, integer path variables and schema attributes generate negative values like "-10968727" despite having examples like "1". Request bodies also have incorrect indentation upon generation, and the validation tool labels these as issues immediately after generation.

Additionally, if Documentation is generated from an OAS with the "Request parameter generation" and "Response parameter generation" options set to "Schema", running validation immediately thereafter results in issues for every such value, and these are then turned into the above-referenced negative values that appear to be coming from nowhere.

### Steps To Reproduce

1. Create an API.
2. Paste in an OAS document (JSON; do not know if it breaks for YAML as well).
3. Generate Documentation from the Overview tab setting the advanced options "Request parameter generation" and "Response parameter generation" to "Schema".
4. Validate the Documentation in the Overview tab, then Review Issues.
5. Look through the issues. It will complain about the auto-generated indentation being wrong and integer values being not negative. Select all issues and click the confirmation button to resolve them.
6. All integers in path variables will be random negative values. Approximately 50% change that request body integers will be replaced with random negative values and 50% change they will be replaced with the example values specified in the OAS.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/4357561/170767939-750c8ee0-7913-4665-a3ac-a71e8b7fa790.png)
![image](https://user-images.githubusercontent.com/4357561/170767997-4dc7e3dd-005a-4fbc-97c4-169292b05d9b.png)

### Operating System

Linux

### Postman Version

9.19.0

### Postman Platform

Postman App

**Comment by kristytoman** [comment]
Hi,
I just ran into this issue and I had a similar problem but I don't know if this is your case too. 

You're talking about setting example to 1 but have you considered setting the minimum value in the schema definition?

Here's mine in YAML:
```
            parameters:
                - name: id
                  required: true
                  in: path
                  description: ID of the user
                  schema:
                      type: integer
                      format: int32
                      minimum: 1
```

Take care!
