### ISSUE TITLE
Add workflow_dispatch for Github Actions CLI command preview template - v10

### ISSUE THREAD

**Issue by Chand-MD** [a85/POSTMan-Chrome-Extension#11320]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

While copying the Postman CLI command overview for Github Actions can we add "**workflow_dispatch**" to the  Build configuration template? This helps the users to run this workflow manually from the Actions tab.

### Describe the solution you'd like

Add "**workflow_dispatch**" to the  Github Actions Build configuration template

**Comment by malvikach** [comment]
@ChandMohammadS thanks for the feedback and for setting up the discussion with us. Looking forward to understand this further during our call.

**Comment by DannyDainton** [comment]
I like the idea of extending the template and we can maybe even pass in some of the different arguments that are available like iterations for example:

```yaml
name: Automated API tests using Postman CLI

on:
  workflow_dispatch:
    inputs:
      iterations:
        description: 'Number of iterations to run'
        required: false
        type: string

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "CollectionUUID" -e "EnvironmentUUID" -n ${{ inputs.iterations || 1 }}
```
