### ISSUE TITLE
Pretty YAML with long keys displays incorrect "?" and ":" characters

### ISSUE THREAD

**Issue by scottydawg** [a85/POSTMan-Chrome-Extension#11984]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Appears to be identical to [the issue described here](https://github.com/prettier/prettier/issues/5599) and may be an issue with the underlying version of Prettier, if that's in fact being used.

When viewing YAML responses in "Pretty" view, long keys appear to be parsed as ternary operations, with a "?" prefix and extraneous ":" characters. These characters are **not** present in "Raw" view.

Some samples in the response:

**Raw**
```yaml
     security:
      - jwtBearerAuth: []
  /workspaces/{workspaceSlug}/databases/{databaseName}/auth/oidc/providers/{providerName}:
    get:
      tags:
```

**Pretty**
```yaml
            security:
                - jwtBearerAuth: []
    ? /workspaces/{workspaceSlug}/databases/{databaseName}/auth/oidc/providers/{providerName}
    : get:
          tags:
```

**Raw**
```yaml
     security:
      - jwtBearerAuth: []
  /workspaces/{workspaceSlug}/databases/{databaseName}/tenants/{tenantId}/users:
    get:
      tags:
```

**Pretty**
```yaml
          security:
                - jwtBearerAuth: []
    ? /workspaces/{workspaceSlug}/databases/{databaseName}/tenants/{tenantId}/users
    : get:
          tags:
```

### Steps To Reproduce

1. Produce an OpenAPI YAML response that contains a resource path (or other key) that is greater than 75 characters long. 
2. Hit that endpoint in Postman
3. View the response in the "Raw" view; expect a valid YAML document
4. View the response in the "Pretty" view; observe that the long key is prefixed with a "?" and suffixed with an incorrect ":".

### Screenshots or Videos

![postman-pretty](https://user-images.githubusercontent.com/923236/236245015-6f986b5c-066e-4d02-b86f-09db48baa2b7.png)
![postman-raw](https://user-images.githubusercontent.com/923236/236245017-9b80e5b0-d83f-46bf-b34d-ced874504b3d.png)

### Operating System

macOS

### Postman Version

10.13.5

### Postman Platform

Postman App

### User Account Type

Signed In User
