### ISSUE TITLE
Change snap.yaml for the theme to work correctly in the application

### ISSUE THREAD

**Issue by YuriyKadysev** [a85/POSTMan-Chrome-Extension#11991]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Please add to the assembly of the snap package the parameters in the snap.yaml file of the line:

```
plugs:
  gtk-3-themes:
    interface: content
    target: $SNAP/usr/share/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/usr/share/icons
    default-provider: gtk-common-themes
```

for the theme to work correctly in the application

### Steps To Reproduce

bash commands:

```
snap download postman
unsquashfs postman_204.snap

```
edit squashfs-root/meta/snap.yaml

add strings:

```
plugs:
  gtk-3-themes:
    interface: content
    target: $SNAP/usr/share/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/usr/share/icons
    default-provider: gtk-common-themes
```

save file squashfs-root/meta/snap.yaml

bash commands:

```
snap pack squashfs-root
sudo snap install ./postman_10.13.0_amd64.snap --dangerous

```
### Screenshots or Videos

![изображение](https://user-images.githubusercontent.com/73478610/236577781-4f073314-07f6-4164-b122-96268e3b6e55.png)

![изображение](https://user-images.githubusercontent.com/73478610/236578122-c6754fcd-a328-4c11-8ac2-cacf8c92d42e.png)

### Operating System

Linux

### Postman Version

10.13.0

### Postman Platform

Postman App

### User Account Type

Signed Out User
