### ISSUE TITLE
Path Parameter Descriptions are not being added 

### ISSUE THREAD

**Issue by stcalica** [a85/POSTMan-Chrome-Extension#12412]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I am experimenting with this OPENAPI Schema YAML in Github. I import and link this OpenAPI Schema YAML in API Builder. 

However, when I generate a collection, the path parameter variable's description does not populate. 
Take a look at the path parameter `spaceshipId`: 

```
paths:
  /spacecraft/{spacecraftId}/passengers:
    parameters:
      - name: spacecraftId
        description: The unique identifier of the spacecrafts please update here. 
        in: path
        required: true
```

Now looking at the collection we do not have the description. 

<img width="1291" alt="CleanShot 2023-10-17 at 11 38 49@2x" src="https://github.com/postmanlabs/postman-app-support/assets/5624835/bbe3820e-5f9d-4633-b977-0dc9d91b8b07">

<img width="1305" alt="CleanShot 2023-10-17 at 11 39 09@2x" src="https://github.com/postmanlabs/postman-app-support/assets/5624835/a8dd5b31-e440-4114-9986-95e22790ce82">

### Steps To Reproduce

1. Go to API Builder and import an OpenAPI schema from Github 
2. Link the Schema to the GitHub repository 
3. Create a path parameter and add a description 
4.  Generate a collection and look at path parameter 

### Screenshots or Videos

<img width="1291" alt="CleanShot 2023-10-17 at 11 38 49@2x" src="https://github.com/postmanlabs/postman-app-support/assets/5624835/bbe3820e-5f9d-4633-b977-0dc9d91b8b07">

<img width="1305" alt="CleanShot 2023-10-17 at 11 39 09@2x" src="https://github.com/postmanlabs/postman-app-support/assets/5624835/a8dd5b31-e440-4114-9986-95e22790ce82">

### Operating System

macOS

### Postman Version

10.19.2

### Postman Platform

Postman App

### User Account Type

Signed In User
