### ISSUE TITLE
OpenAPI to collection: when parsing the body schema for a PATCH (application/x-www-form-urlencoded), flatten nested structures with bracket notation

### ISSUE THREAD

**Issue by k98kurz** [a85/POSTMan-Chrome-Extension#13472]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

OpenAPI specs are difficult to use due to many issues with parsing body schemas, particularly with PATCH requests and nested schemas.

### Describe the solution you'd like

When generating the form contents for an application/x-www-form-urlencoded PATCH request, flatten nested properties in the body schema. For example:

```yaml
  type: object
  properties:
    mappings:
      type: object
      properties:
        fields:
          type: object
        names:
          type: object
```

Results in this:
![image](https://github.com/user-attachments/assets/9dc0b5ac-cdd0-49be-be23-953dc99514ca)

It should result in something like this:
![image](https://github.com/user-attachments/assets/e7a87998-c7ea-46c1-a2f3-88d4826d861e)

### Describe alternatives you've considered

Omitting the `[key]` and replacing `value` with `<object>`, which would still be an improvement:

![image](https://github.com/user-attachments/assets/dceee309-9c5a-4b61-b85d-c70b87dda3ca)

**Comment by barshan23** [comment]
Hey @k98kurz thanks for reaching out!

I went through the sample you provided. 

The schema is missing a serialisation strategy. That needs to be provided to explain how to serialise these object / array type parameters. [Ref](https://swagger.io/docs/specification/v3_0/describing-request-body/describing-request-body/#:~:text=The%20serialization%20strategy%20is%20specified%20in%20the%20encoding%20section%20like%20so)

```
application/x-www-form-urlencoded:
  schema:
    type: object
    properties:
      username:
        type: string
      password:
        type: string
      tags:
        type: array
        items:
          type: string
        description: List of tags the user is associated with.þ
      address:
        type: object
        properties:
          street:
            type: string
            description: The street name.
          city:
            type: string
            description: The city name.
          zip:
            type: string
            description: The postal code.
        description: The user's address.ad
  encoding:
    tags:
      style: form
      explode: true
    address:
      style: deepObject
      explode: true
```

Here is one such example on how to define that in OAS.

And here is what the generated collection looks like

![Image](https://github.com/user-attachments/assets/0eee3893-e050-405d-a41b-29e74412b38b)

<img width="1097" alt="Image" src="https://github.com/user-attachments/assets/f66454d3-61e4-44d7-ae17-2658b706e9d8" />

Let me know if this answers your query.
