### ISSUE TITLE
Swagger import - Security definition  and Schemes ignored

### ISSUE THREAD

**Issue by RitwikChatterjee** [a85/POSTMan-Chrome-Extension#1470]
Hi,
When I am importing Swagger definition into POSTMAN, the securitydefinition is ignored.
Also, I am not able to find all the schemes that I am defining.
FYI, here is what I have used:

schemes:
- http
- https
  securityDefinitions:
  basicAuth:
    type: basic
    description: HTTP Basic Authentication.

**Comment by abhijitkane** [comment]
@RitwikChatterjee The first part (scheme - https) has been fixed, and we'll push it in the next release.

Support for Basic Authentication is not present yet, we'll add it in a future release (can't offer an ETA on it though)

**Comment by theManikJindal** [comment]
@abhijitkane I face the same issue when importing a swagger with `securityDefinition` type `oauth2`. There is no Auth imported at all in any of my APIs even though the `security` object is present on each of them. 

Should I log a separate issue?

**Comment by TheCodeDestroyer** [comment]
Is it possible to have anything in schemes I would like to import that as a variable.

Example:

```
schemes:
 - "{{protocol}}"
```

I know this is not a valid swagger file but it's easier for me to change it here than after the import for 100+ endpoints

**Comment by theManikJindal** [comment]
@TheCodeDestroyer I think that would be a separate feature request. Maybe you would want to add a new issue for that.

**Comment by coolbung** [comment]
Do you support the security definitions yet ? I have the following securityDefinition in my swagger file
```yaml
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: "header"
```

but postman seems to be ignoring it when importing the swagger file.

**Comment by liemle3893** [comment]
Any work on this issue?
I'm still having problem with Swagger Security.
```yaml
swagger: "2.0"
.
.
securityDefinitions:
  APIKeyQuery:
    type: apiKey
    in: query
    name: auth_key
  APIKeyHeader:
    type: apiKey
    in: header
    name: Authorization
```
Thanks!

**Comment by meantux** [comment]
Multiple API Keys' not really supported
In my example below you'll find a security defined as Swagger documented. Please note the second item does not have a dash, this is to indicate that they are both needed for the query. When I import it into Postman only the first security key is visible.

```
security:
  - PNClientId: []
    PNToken: []

components:
  securitySchemes:
    PNClientId:
      type: apiKey
      in: header
      name: x-client-id
    PNToken:
      type: apiKey
      in: header
      name: x-authentication-token

```
