### ISSUE TITLE
Better RAML 0.8 import behavior

### ISSUE THREAD

**Issue by maxmarkus** [a85/POSTMan-Chrome-Extension#1845]
Hello, 

I'd like to see some raml import improvements. Currently I'm importing raml, then exporting collection and do search-replace along for lots of query params and path values.

It would be great to see things like:
- taking automatically default value if available (query params). currently it looks like `endpoint?fields=&pageSize=` and its necessary to change or delete all manually. raml definition for eg. pageSize:
  
  ```
      pageSize: 
          description: |
              The number of documents being retrieved on the page.
          type: integer
          required: false
          repeat: false
          minimum: 1
          default: "16"
          example: `"16"`
  ```
- if no default value defined, add the descriptor as variable 
  
  ```
    ..api../accounts/:email/terms
   would be  {{email}}
  ```
- if "required" is false, disable this by element default
- same for params, would be great to be able to disable them too

I'm using your great Mac App v4.0.5
