### ISSUE TITLE
Feature request: automated project generation

### ISSUE THREAD

**Issue by dsgn1graphics** [a85/POSTMan-Chrome-Extension#3074]
I'll try my best to describe my idea, but I think this would be a very cool feature. It would be awesome if Postman supported a language, that allowed us to define specific rules within our files. These could be pulled into Postman to create projects. If this feature has already been mentioned, please close this. I searched for something similar but couldn't find anything documented.

Issues to solve: 
* Remove the need for excessive coping and pasting when setting up API endpoints to test with.
* Alleviate the need for remembering to update and share changes with other developers.
* Offer the ability for teams to manage and store the Postman project configurations in source control. 
* Reduce the setup time for for development.
* Improve the overall experience

Here's an example of what I'm talking about.

Within the project root, define a `.postman{.env}` (json, yaml, or whatever format..) config file, which is read into Postman and defines a few rules and defaults. For example

```
# my_project_root/.postman.dev

# Define directories and file types the parser should limit access to while looking for the @Postman flag, this would also speed up processing time, since some projects have thousands of files.
read_dir: app/controllers/api/v1/*/**.rb
read_dir: app/controllers/api/v2/*/**.rb

# Define default headers for every request. For projects that don't implement a strict SSO policy, setting a default user authorization header could be helpful
headers:
  authorization: Token-123456...
  content-type: application/json
  accepts: application/json
  ... # more headers

# In development environments the host rarely changes. By appending the `[.env]` for specific environments to the config file, postman can pull in multiple configurations and generate complete test suites on the fly for all api environments if needed. 
host: http://localhost:3000/api/v1/

# Additional configurations or rules can be listed here also. For example rules like allow and deny tell the parser to process or skip over certain items.
allow: 
  method: GET, POST, PATCH, PUT DELETE
  status: ACTIVE
deny: 
  status: DEPRECATE
```

Once the config file has been defined in the project root, it's time to write some samples in my code. Here, I'm updating my pets controller with some custom Postman syntax so the parser knows that I want a to create a few test endpoints for these methods.

```ruby
# my_project_root/app/controllers/api/v1/pets.rb

class PetsController < ApplicationController

  # @Postman
  # @Postman-namespace: api/v1/pets (this defines the directory/subdirectory that postman should create and/or place this query under so I can find it later)
  # @Postman-path: pets (this is the path that will be appended to the end of the host defined in the config file
  # @Postman-param: page (query params to append to the end of the path when building a url)
  # @Postman-param: limit
  # @Postman-headers-cache-control: max-age 2000 (could define additional headers to be created for this specific request)
  # @Postman-method: GET
  # @Postman-status: ACTIVE
  # @Postman-desc: This request returns all of the pets for this current user
  # Some other dev notes here (Postman declarations shouldn't interfere with normal comments)
  #
  def index page = 1, limit = 20
    user = authenticated_user
    page = params[:page] ? params[:page] : page
    limit = params[:limit] ? params[:limit] : limit

    @pets = Pets.where( user_id: user.id ).offset( (page * limit) - 1 ).limit( limit )
    render 'pets/list.json' # render some file that defines the json output or just dump json into the output stream, whatever your api does is cool
  end

  # @Postman
  # @Postman-namespace: api/v1/pets (this defines the directory/subdirectory that postman should create and/or place this query under so I can find it later)
  # @Postman-path: pets (this is the path that will be appended to the end of the host defined in the config file
  # @Postman-headers-cache-control: no-cache (could define additional headers to be created for this specific request)
  # @Postman-method: POST
  # @Postman-status: ACTIVE
  # @Postman-body: {'name': 'Foo', 'type': 'dog', 'age': '3'} (define a body template for some request like POST, PUTS, and PATCH)
  # @Postman-test: [{'name': 'Foo', 'type': 'dog', 'age': '3'}] (define a test response)
  # @Postman-desc: This request creates a new pet
  # Some more dev notes here (These shouldn't interfere with normal comments either)
  #
  def create
    @pet = Pet.new(post_params)
    if @pet.save
      render 'pets/show.json'
    else
      render json: @pet.errors, status: 422
    end
  end

  # @Postman
  # @Postman-namespace: api/v1/pets (this defines the directory/subdirectory that postman should create and/or place this query under so I can find it later)
  # @Postman-path: pets/{id} (this is the path that will be appended to the end of the host defined in the config file. It also defines a replacement param, which should be allowed to pass through. This reminds the user that the url needs to be updated prior to sending this request
  # @Postman-headers-cache-control: no-cache (could define additional headers to be created for this specific request)
  # @Postman-method: DELETE
  # @Postman-status: DEPRECATED
  # @Postman-desc: This request deletes a pet, deprecated... :(
  # Removing this method soon since we're switching to a archive system
  #
  def delete
    @pet = Pet.find(123).destroy
    if @pet
      render 'pets/show.json'
    else
      render json: @pet.errors, status 422
    end
  end


  # .... More api methods and code defined bellow
end
```

Now that I've done all of the tagging on my end is done, I should be able to load my new config into Postman from the navigation menu. After authorizing file system access on my computer, Postman is cleared to read my config file and create a new project for me programmatically. All all of my api endpoints with default settings should be created. If I'm satisfied with everything, I can commit the changes in my repo and push them up for other developers on my team to use. If I need to make changes, I can simply update my comments or config file and reload the project from navigation menu to pull the newest changes. 

I won't go into detail about how that should be implemented in the application, but hopefully you guys have a good idea of what I'm talking about. Also, I know there are some common protocols already out that use the `@somekey: some value` syntax for generating documentation. There may be a way to piggy back or extend what's already out there so that updating an entire code base won't be necessary for those project that already have something in place.
