### ISSUE TITLE
How to join files spec in one big file

### ISSUE THREAD

**Issue by asyba** [a85/POSTMan-Chrome-Extension#5652]
How the relative path reference works? I have a project with this in the openapi.yaml root file but when I copy this to the editor, it doesn't fill the content using each file inside of the project. So this is super frustrating how I can export my swagger project for example to postman? If my swagger project contains a lot of files and Postman only need 1 file.

```
components:
  requestBodies:
    NewProgram:
      $ref: "./components/requestBodies/new-program.yaml"
    UpdateProgram:
      $ref: "./components/requestBodies/update-program.yaml"
    NewContactPreference:
```

**Comment by abhijitkane** [comment]
@asyba Since Postman only supports single-file schemas, you'll need to use something like https://github.com/maxdome/swagger-combine to convert your files to a single-file spec.

**Comment by asyba** [comment]
> @asyba Since Postman only supports single-file schemas, you'll need to use something like https://github.com/maxdome/swagger-combine to convert your files to a single-file spec.

Thanks!

* I am pretty close got some errors in the editor:
```
Schema error at paths['/member'].get.parameters[0].required
should be equal to one of the allowed values
allowedValues: true
Jump to line 31
```

```
paths:
  /member:
    get:
      tags:
        - InProgress
      summary: Lists Members based on the filter
      description: Lists Members based on the filter
      parameters:
        - name: name
          in: query
          description: >-
            Filters for Members with lastName/firstName, returns the array based
            on filter.
          required: false
        - name: id
          in: query
          description: 'Filters Members with id, returns the array based on filter.'
          required: false
        - name: dateOfBirth
          in: query
          description: >-
            Filters for Members with dateOfBirth like "2018-12-10", returns the
            array based on filter.
          required: false
```

* also if I want to import in SoapUI will happen the same like Postman? It requires single file?
