### ISSUE TITLE
Import schema with Postman variables

### ISSUE THREAD

**Issue by marcofiocco** [a85/POSTMan-Chrome-Extension#7311]
**Describe the bug**
I've tried to import OpenAPI 3 schema but every time I create a collection out of it I have to manually enter again the Postman variables I want to use to parametrize the environments.
Is there a way to define these in the schema?

**To Reproduce**
1. Create a collection out of an OpenAPI 3 schema
2. Select an endpoint in a collection and enter Postman variable in one of the input parameters
3. Create another collection out of the same OpenAPI 3 schema
4. Repeat 2

**App information (please complete the following information):**
 - Native app
 - Postman Version 6.7.0
 - macOS 10.14.6

**Comment by jehrlich** [comment]
openapi allows customization. Maybe It could work something like
```
            schema:
              type: object
              properties:
                username:
                  type: string                  
            example:
              username: 
                  x-postman-variable: myVar
```
which postman would translate to example data `username: {{myVar}}`
