### ISSUE TITLE
Missing example data when importing openapi3 in postman v7.9.0

### ISSUE THREAD

**Issue by MarKco** [a85/POSTMan-Chrome-Extension#7477]
I'm importing a swagger openapi 3.0.0 file in Postman. I have some example data in swagger that I'd like to be synchronized in the postman collection.

Example of example data:

```
RestaurantPayload:
  type: object
  properties:
    google_places_id:
      type: number
      format: integer
    name:
      type: string
    city:
      type: string
    cover_image:
      type: string
    latitude:
      type: number
      format: double
    longitude:
      type: number
      format: double
    rating:
      type: number
      format: float
    categories:
      type: array
      items:
        type: string
  example:
    google_places_id: 561
    name: "Very cool restaurant"
    city: "Rome"
    cover_image: "http://my-picture-url.jpg"
    latitude: 39.485855
    longitude: 49.48585747
    rating: 4
    categories: [
      "sushi"]
```

I tried three different ways:

1- Importing the JSON/YAML as it's exported from swagger directly in Postman. It works and I get the collection with all the methods I'm looking for BUT I'm missing example data. For instance

![HcuZ4](https://user-images.githubusercontent.com/1422362/66832404-221e0a80-ef5a-11e9-9d17-1b4fd3952a26.png)

2- Converting the openapi file to postman using the postman command line converter (https://github.com/postmanlabs/openapi-to-postman) Same situation, example data is missing

3- Using an external service as APImatic (https://www.apimatic.io) This is the only way I managed to get a Postman JSON which - once imported in the postman app - keeps all example data in place

![9LPGG](https://user-images.githubusercontent.com/1422362/66832416-2a764580-ef5a-11e9-981a-8a7e60759527.png)

I'd really like NOT to need an external service to perform this task and to be able instead to translate my openapi specifications to postman with all the example data with a command line tool or something similar.

Do you happen to know why is this happening and how I can get what I need?

Thank you Marco

Edit: the APImatic solution doesn't seem to be viable because it breaks the endpoints.

APImatic:

![Selection_539](https://user-images.githubusercontent.com/1422362/66911716-615b6280-f011-11e9-8463-a3dc79b2dcaa.png)

YAML import from Swagger

![Selection_540](https://user-images.githubusercontent.com/1422362/66911729-65878000-f011-11e9-882c-d0d7d7e38afd.png)

So I'm stuck, one import method breaks the endpoints while the other breaks the examples :-/

**Comment by MarKco** [comment]
I edited the issue with some further details

**Comment by jehrlich** [comment]
I find that Postman will import example data if it is provided in openapi.yaml within the request at the ` schema` level, but not using  `$ref`, or in child objects. This does need to be fixed because the workaround is very un-DRY.

For example, this snippet works for me, but defining a data object which includes an example then referring to it with `$ref` does not.:
```
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string                  
                password:
                  type: string
            example:
              username: aUser
              password: apass
```

**Comment by jehrlich** [comment]
I found a more DRY way to do an example in openapi.yaml so that Postman imports it correctly. Define your example as a `component` , like in the OAS3 snippet below `example-123` is a key value chosen by me and the example object is added as the value for the `value:` entity. 
```
components:
  examples:
    example-123:
      value:
```
Then you can reference your example like 
```
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                obj:
                  $ref: '#/components/schemas/obj'
            example:
              $ref: '#/components/examples/example-123'

```
