### ISSUE TITLE
API default authorization

### ISSUE THREAD

**Issue by jehrlich** [a85/POSTMan-Chrome-Extension#7643]
When I import my OAS3 API spec with 
```
security:
 - AuthToken: []

components:
  securitySchemes:
    AuthToken:
      type: apiKey
      in: header
      name: X-Auth-Token
```
the header key is added to each request. I would like the value to be `{{token}}` so I can authenticate from the environment, but I can't see a way to do that without pasting the value into each endpoint manually.

As a kludge, I could remove the `security:` from the API in Postman, and use Postman authentication. The catch with that is that default auth scheme for folders is  `inherit auth from parent` but each individual request is set to `no auth` which supersedes the parent setting. This means I need to visit each endpoint to change it back to inherit, then manually set the authentication for the parent. 

**Expected behavior**
1. The security scheme from the OAS3 doc should be imported into Postman's authentication model, and there should be a means to incorporate Postman environment variables. In the configuration above that would make `X-Auth-Token` a temporary header.
2. Failing that, endpoints should default to `inherit from parent`.
