### ISSUE TITLE
InvalidAccessError when importing a RAML file that references an example

### ISSUE THREAD

**Issue by dkirrane** [a85/POSTMan-Chrome-Extension#822]
![postmanramlfail](https://cloud.githubusercontent.com/assets/1280116/5128055/6274f6b0-70d0-11e4-9a1e-d2a8cc812e82.png)

RAML has the following:

```
    /resource:
      post:
        description:
        body:
          application/json:
            example: !include examples/QueryResourceRequest.json
```
