### ISSUE TITLE
CircleCi Newman Integration Broken

### ISSUE THREAD

**Issue by jackpeeples** [a85/POSTMan-Chrome-Extension#8695]
On CircleCi, I want to run a suite of postman tests, from a collection, in my pipeline. When I attempt to use the newman orb (postman/newman@0.0.2) I get the error: "Either git or ssh (required by git to clone through SSH) is not installed in the image"
This only occurs when attempting to use a local json version of the collection - not when using the sharable link. The problem lies in circleCi not being able to reference the git (bitbucket in my case) repo and thus not being able to run the collection.

To reproduce, set up a simple project with a circle ci integration. Add a step, like the following, into the workflow.

  run_postman_tests:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: collections/sample_collection.postman_collection.json

What is expected is to execute the suite of postman tests.

**Comment by DannyDainton** [comment]
Hey @jackpeeples 

Could you try running it with this config:

```yml
version: 2.1
orbs:
  newman: postman/newman@0.0.2
jobs:
  build:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: ./collection.json
```
I saw a similar question around this in a different forum and the missing `build` step was to blame - might be worth giving it a go, to rule it out.

**Comment by jackpeeples** [comment]
I have tried it, and it did not solve the issue. "build:" is the keyword for the job name in circleCi.I have a different job name but tried both adding it under the job name and replacing the job name with "build" and both failed, unfortunately. Thanks for the suggestion, however!

**Comment by DannyDainton** [comment]
Ah, that's a shame @jackpeeples,

All you able to provide the full config file or something that we can easily reproduce the issue with, I'm having trouble seeing the same thing from my end 🤔

**Comment by jackpeeples** [comment]
It is occurring with the job step defined exactly as it is in the orb registry (https://circleci.com/orbs/registry/orb/postman/newman), except the orb version is 0.0.2 rather than 1.0.0, as circle ci rejects 1.0.0 as not existing. Also, I changed the job name but I believe that is just a label. 

like so 

at the top:
version: 2.1
orbs:
  newman: postman/newman@0.0.2

later in the config: 
jobs:
  run-postman-tests:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: ./sample_collection.collection.json

when that job is run, the error mentioned in the original comment occurs on the checkout step. All the research I've done on this error says it is a problem with the executor specifically and needs to be taken up with the owner of the orb, so my hands are tied. 

however, fortunately, I have found a workaround that gets the job done. I created an earlier job that persists the needed files to the workspace from our repo. Then I can reference the collection in the workspace, during the step mentioned above, and all works properly, as long as I don't try to download our workspace in the same step. The problem seems to be, especially due to the reference of git in the error message, the orb's ability to reference a git repo. 

Thanks in advance for any help!

**Comment by DannyDainton** [comment]
We'll get the documentation sorted within the Orb repo, that should be displaying the wrong versions in there :( 

I'm still not seeing in failing to pick up the local files like you originally mentioned. I'm using a basic example here but it's picking up the files from that file path in my GH repo:

```yml
version: 2.1
orbs:
  newman: postman/newman@0.0.2
jobs:
  build:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: ./tests/Restful_Booker_Collection.postman_collection.json
          environment: ./tests/Restful_Booker_Environment.postman_environment.json
```

I did see the error message you mentioned during the `checkout` phase but that didn't impact the Newman run and the collection was run and returned as I would expect it to.

![Screenshot 2020-06-24 at 14 54 26](https://user-images.githubusercontent.com/17089546/85570644-6e623400-b62b-11ea-8fda-3229d480ccda.png)

The only time I saw it `fail` was when I changed the Collection file name in the config file. Are you able to run my basic config file and swap out the `collection` filename and path to it in your repo?

An image of what you're seeing or one of when it's not running the tests would help us to narrow down the issue.
