### ISSUE TITLE
Path variable created from schema is not replaced with it's value when the request is sent

### ISSUE THREAD

**Issue by Lacni135** [a85/POSTMan-Chrome-Extension#8720]
**Describe the bug**
Path Variables from a generated collection from an OpenApi 3.0 schema are wrongfully interpreted (The path variable "userId" needs to be of type integer, but we found ":userId") even though the value in the field is ok

**To Reproduce**
1. Create an OpenApi 3.0 schema with a path parameter like such:
```
 '/users/{userId}':
    parameters:
      - schema:
          type: integer
          example: 3
          default: 1
          minimum: 1
          exclusiveMinimum: false
        name: userId
        in: path
        description: Id of the user to pull details of
        required: true 
```
2. Generate a collection using the schema (In my case, generated an API documentation collection).
3. Go to the generated collection and go to the path.
4. Inside the params tab of the request, the path variable is there with the correct value but sending the request doesn't replace the variable with the value.

**Expected behavior**
The path variable should be replaced with it's corresponding value when the request is sent

**Screenshots**
![image](https://user-images.githubusercontent.com/11847370/86052630-4ad12c00-ba25-11ea-9def-b3c847832b29.png)

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version v7.27.1
 - OS: [e.g. macOS Catalina 10.15.5]

**Additional context**
Removing the variable and rewriting it fixes the issue
