### ISSUE TITLE
Can't send POST requests to Elasticsearch using raw JSON body

### ISSUE THREAD

**Issue by garstas** [a85/POSTMan-Chrome-Extension#8764]
**Describe the bug**
When I try to send a POST request with a raw JSON body to elastic host - error `request body is required` is returned.

**To Reproduce**
1. Run Elasticsearch instance, for example, using this simple `docker-compose.yml` snippet (no additional setup required, `docker-compose up` command will boot the service on 81 port ready to send requests to test the error):
```
version: "3"

services: 
    elastic:
        image: elasticsearch:7.8.0
        container_name: elastic
        ports: 
            - 81:9200
        environment:
            - node.name=es01
            - cluster.name=es-docker-cluster
            - discovery.type=single-node
```
1. Create new request to an empty elastic installation `localhost:81/logs/my_app`
![image](https://user-images.githubusercontent.com/19244786/87234019-af9d6680-c3d5-11ea-894b-a8c910a25ee1.png)
![image](https://user-images.githubusercontent.com/19244786/87234137-b678a900-c3d6-11ea-893b-87fa25782a12.png)
![image](https://user-images.githubusercontent.com/19244786/87234149-d6a86800-c3d6-11ea-9143-ac6ffab1642f.png)

2. Click "Send" and get:
```json
{
    "error": {
        "root_cause": [
            {
                "type": "parse_exception",
                "reason": "request body is required"
            }
        ],
        "type": "parse_exception",
        "reason": "request body is required"
    },
    "status": 400
}
```

**Expected behavior**
If I send this request using curl 
```bash
curl -X POST 'localhost:81/logs/my_app' -H 'Content-Type: application/json' -d'
{
        "timestamp": "2018-01-24 12:34:56",
        "message": "User logged in",
        "user_id": 4,
        "admin": false
}
'
```

The result is expected:
```
{
    "_index": "logs",
    "_type": "my_app",
    "_id": "SSTLP3MBoe1a6iJ__ZAt",
    "_version": 1,
    "result": "created",
    "_shards": {
        "total": 2,
        "successful": 1,
        "failed": 0
    },
    "_seq_no": 1,
    "_primary_term": 6
}
```

**Screenshots**
Added them above

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: Postman for Linux | Version 7.27.1 | linux 5.7.1-050701-generic / x64
 - OS: Ubuntu 18.04

**Additional context**
The curl request generated by postman (i got it by pressing "Code" button in postman GUI) is correct:
```
curl --location --request POST 'localhost:81/logs/my_app' \
--header 'Content-Type: application/json' \
--data-raw '{
	"timestamp": "2018-01-24 12:34:56",
	"message": "User logged in",
	"user_id": 4,
	"admin": false
}
'
```
And I'm surprised that the actual request sent by postman is not. Am I missing something here?
