### ISSUE TITLE
Manage Environments window needs to be larger - 750px is not enough

### ISSUE THREAD

**Issue by thetreythomas** [a85/POSTMan-Chrome-Extension#8993]
**Is your feature request related to a problem? Please describe.**
When you have the "MANAGE ENVIRONMENTS" window open to add variables, or add a new environment, the 750px width this is set to is not enough, especially if you are adding JSON data to either the initial or current values.

**Describe the solution you'd like**
Looking at the Developer Tools, you have the height set to 70vh, and the width to 750px. Changing the width to 80vh was the perfect amount for me.

This window is not draggable, you can't do anything else while this is open, so why restrict the size if this is the main focus for what the user is working with?
```css
element.style {
    position: relative;
    border: none;
    background: transparent;
    overflow: hidden;
    border-radius: 3px;
    outline: none;
    padding: 0px;
    width: 750px;
    margin-top: 15vh;
    height: 70vh;
}
```

div info
![image](https://user-images.githubusercontent.com/15376624/91527203-ea4a5800-e8ca-11ea-9d73-6d12fd44d870.png)

**Describe alternatives you've considered**
None

**Additional context**
None
