### ISSUE TITLE
Openapi (OAS 3.0) deepObject incorrect rendering on import.

### ISSUE THREAD

**Issue by n2ygk** [a85/POSTMan-Chrome-Extension#9053]
**Describe the bug**
Import of a deepObject parameter definition results in incorrect query parameters.

**To Reproduce**
1. Import the attached example openapi spec file which has this definition:
   ```yaml
    fields:
      name: fields
      in: query
      description: '[sparse fieldsets](https://jsonapi.org/format/#fetching-sparse-fieldsets)'
      required: false
      style: deepObject
      schema:
        type: object
      explode: true
   ```
2. Look at the query parameters generated, e.g. for the GET of /v1/Courses: `&fields[0]=<&fields[1]=o&fields[2]=b&fields[3]=j&fields[4]=e&fields[5]=c&fields[6]=t&fields[7]=>` and note that this is the word <object> spelled out.

**Expected behavior**
Not quite sure other than perhaps ignore deepObjects when converting to query parameters. Certainly spelling out the word `<object>` is not the right behavior.

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version 7.31.1 (7.31.1)
 - OS: macOS Catalina 10.15.6 (19G2021)

[t4.yaml.txt](https://github.com/postmanlabs/postman-app-support/files/5214548/t4.yaml.txt)

**Comment by VShingala** [comment]
@n2ygk Thanks for reporting issue.

The issue is happening due to wrong handling of empty objects, which is fixed with https://github.com/postmanlabs/openapi-to-postman/pull/294 and should be available in App with upcoming releases.

This will mean that for mentioned parameter object no query params will be added.

Also just to confirm that issue is present only when no properties are mentioned for schema with type `object`. And current behaviour is whenever properties are present, they should be to added as query params for each property.

i.e. for following query

```
name: fields
in: query
description: '[sparse fieldsets](https://jsonapi.org/format/#fetching-sparse-fieldsets)'
required: true
style: deepObject
schema:
  type: object
  properties:
    hello:
      type: string
    world:
      type: integer
explode: true
```

below mentioned query params should be present.
```
fields[hello] = <string>
fields[world] = <integer>
```

**Comment by n2ygk** [comment]
@VShingala Thanks! For the time being I've changed my definition like this:
```yaml
    fields:
      name: fields
      in: query
      description: '[sparse fieldsets](https://jsonapi.org/format/#fetching-sparse-fieldsets).

        Use fields[\<typename\>]=field1,field2,...,fieldN'
      required: false
      style: deepObject
      schema:
        type: object
        properties:
          <typename>:
            type: string
      explode: true

```

This generates a single query parameter like this: `fields[<typename>]=<string>`

**Comment by VShingala** [comment]
@n2ygk This issue has been resolved with the latest App release v7.33. Closing this for now.

**Comment by n2ygk** [comment]
> @n2ygk This issue has been resolved with the latest App release v7.33. Closing this for now.

@VShingala I don't think this is fixed. I'm seeing the same behavior with v7.35 for this:
```yaml
    fields:
      name: fields
      in: query
      description: '[sparse fieldsets](https://jsonapi.org/format/#fetching-sparse-fieldsets).

        Use fields[\<typename\>]=field1,field2,...,fieldN'
      required: false
      style: deepObject
      schema:
        type: object
      explode: true
```

![image](https://user-images.githubusercontent.com/4356471/98247601-d31a8d00-1f41-11eb-923b-fea81592d898.png)
