### ISSUE TITLE
Schema Validation not working when Path Templating and Fixed Paths overlap

### ISSUE THREAD

**Issue by darrencapner** [a85/POSTMan-Chrome-Extension#9396]
**Describe the Issue**

I am trying to define an Openapi spec where I have the following paths:

/{id}
/lookups
When I perform a validation on the collection within the API Designer the API Designer Collection validator does not understand a fixed path where there exists a path with a wildcard. The merge window evaluates both paths as one and the suggested merge is nonsensical.

**Steps to Reproduce**

Definition used below that is causing issues:

```
/lookups:
    get:
      summary: Lookup Job Values
      description: Lookup values for job fields
      operationId: lookupJobValues
      security:
        - authorizer: []
      parameters:
        - in: path
          name: include
          schema:
            type: string
          required: true
          description: Unique value to return list of possible job field values.
          example: "cancellationReasons"
/{jobid}:
    get:
      summary: Get Job by ID
      description: |
        Retrieve a job by the identifier provided.
        Query Parameters supported are:
        * 'include' will return related entities to a Job. Can ask for 'quote' at this time.
      operationId: getJobById
      security:
        - authorizer: []
      parameters:
        - in: path
          name: jobid
          schema:
            type: string
          required: true
          description: Unique identifier for a job to retrieve.
          example: "{{jobid}}"
        - in: query
          name: include
          schema:
            type: string
            example: quote
          required: false
          description: Include related entities to a Job to be returned in request. Can ask for 'quote' at this time.
```

**Screenshots or Videos**
![Postman_conflict_merge_screen](https://user-images.githubusercontent.com/30915037/103546566-d01c1a00-4e68-11eb-967b-bd99fe328ffc.png)

**Environment Information**

 - Platform Type: [e.g. Postman On The Web]
 - Postman Version: December 28th, 2020
 - Operating System: Windows / Chrome Browser

**Additional Context**

[Postman Community Post](https://community.postman.com/t/schema-validation-not-working-when-path-templating-and-fixed-paths-overlap/18725)
