### ISSUE TITLE
Contract testing response from Collection Request using API Designer Component Schema from API Spec

### ISSUE THREAD

**Issue by darrencapner** [a85/POSTMan-Chrome-Extension#9408]
**Is your feature request related to a problem? Please describe.**
The feature request is related to the ability to validate a collection's request in tests without duplicating and manually converting the API Designer component schema in OpenAPI 3.0 to JSON Schema and storing it as an escaped string in an environment variable. This causes duplication, manual effort on each change, and easy potential for schemas to get out of sync.

**Describe the solution you'd like**
In a test for a collections request, I would like to validate the response not using a JSON schema stored in an environment variable but reference the API Designer component schema for the response that the collection request was derived from.

Currently we have to do this which validates the response using a JSON schema that exists in environment variables.

```
// test that the response is valid by comparing against schema
var response_schema = JSON.parse(JSON.parse(pm.environment.get('create_carrier_response_schema')));

var Ajv = require('ajv'),
    ajv = new Ajv({logger: console, verbose: true}),
    schema = response_schema;

pm.test('Schema is valid', function() {
    var data = pm.response.json();
    pm.expect(ajv.validate(schema, data)).to.be.true;
});
```
I would like to do something similar but pull the schema from the API spec the collection was derived from. An example API Designer OpenAPI 3.0 component schema below and the desired code to validate a response using it.

```
components:
  schemas:
    Response:
      title: "Response Schema"
      required:
        - "status"
        - "code"
        - "message"
      type: "object"
      properties:
        status:
          type: integer
        code:
          type: integer
        message:
          type: string
```

```
// test that the response is valid by comparing against schema
var response_schema = // Get schema from API.components.schemas.Response

var Ajv = require('ajv'),
    ajv = new Ajv({logger: console, verbose: true}),
    schema = response_schema;

pm.test('Schema is valid', function() {
    var data = pm.response.json();
    pm.expect(ajv.validate(schema, data)).to.be.true;
});
```

**Additional context**
Link to Postman community page for first mention of this feature request. [API Designer Contract Testing Reference Schema from API Spec](https://community.postman.com/t/api-designer-contract-testing-reference-schema-from-api-spec/13322)
